#!/usr/bin/env /usr/bin/python

import os
import sys


def main(argv):
    product_git_src = argv[1]
    product_dir_tmp = "repo/_init/product"
    product_file_property = product_dir_tmp + "/property"
    os.system("rm -rfv " + product_dir_tmp)
    os.system("git clone " + product_git_src + " " + product_dir_tmp)
    product_property = open(product_file_property)
    product_property.close()
    

if '__main__' == __name__:
	main(sys.argv[0:])

